### PR TITLE
Fixes to the OAuth redirect URL when the use-store-code in URLs is enabled

### LINKED ISSUE #186: If store codes are added to the URLs the we are creating bad Oauth redirection URL
If setting `Add Store Code to Urls` is set to `yes` constructing the following URLs fails (no `___store` parameter is added into Nosto URLs)
- Oauth redirection URL
- Product URL

### LINKED ISSUE #206: Configurable products don't have the availability set correctly on the observer
In a multi-store setup, there seems to be an issue that configurable products have the availability always set to `OutOfStock`. This is due to the fact that the store context is not set correctly in the observer.

### PR DESCRIPTION
**Pull request by hannunosto**
Closes #186 
Closes #206

### CODE REVIEW

File: app/code/community/Nosto/Tagging/Helper/Url.php [hunk 1]
```diff
@@ -260,4 +260,51 @@ public function getFrontPageUrlForStore(Mage_Core_Model_Store $store)
...
+    {
+        /* @var Nosto_Tagging_Helper_Data $configHelper */
+        $configHelper = Mage::helper('nosto_tagging');
+        if ($configHelper->getAddStoreCodeToUrlPath($store)) {
+            $url = Mage::getUrl(
+                'nosto/oauth',
+                array(
+                    '_store' => $store->getId(),
+                    '_store_to_url' => false,
+                    '_type' => Mage_Core_Model_Store::URL_TYPE_WEB,
```
Comment (mridang) [inline app/code/community/Nosto/Tagging/Helper/Url.php]: Should this be URL_TYPE_LINK?

File: app/code/community/Nosto/Tagging/Helper/Url.php [hunk 2]
```diff
@@ -260,4 +260,51 @@ public function getFrontPageUrlForStore(Mage_Core_Model_Store $store)
...
+                )
+            );
+            $baseUrl = $store->getBaseUrl();
+            $urlParts = explode($baseUrl, $url);
```
Comment (mridang) [inline app/code/community/Nosto/Tagging/Helper/Url.php]: Seems hackish. I would double remove the scheme before comparing i.e. `http://` or the `https://`

File: app/code/community/Nosto/Tagging/Helper/Url.php [hunk 3]
```diff
@@ -260,4 +260,83 @@ public function getFrontPageUrlForStore(Mage_Core_Model_Store $store)
...
+                $newUrlParts['query']
+            );
+        } else {
+            $finalUrl = $url;
+        }
+
+        return $finalUrl;
+    }
+
+    public static function removeLeadingAndTrailingSlash($string)
```
Comment (mridang) [inline app/code/community/Nosto/Tagging/Helper/Url.php]: Why not just use trim?

File: app/code/community/Nosto/Tagging/Helper/Url.php [hunk 4]
```diff
@@ -260,4 +260,83 @@ public function getFrontPageUrlForStore(Mage_Core_Model_Store $store)
...
+                'path' => implode('/', $newPathParts),
+                'query' => '',
+            );
+            if (isset($oauthUrlParts['query'])) {
+                $newUrlParts['query'] = $oauthUrlParts['query'];
+            }
+            $finalUrl = sprintf(
+                '%s://%s/%s?%s',
+                $newUrlParts['scheme'],
+                $newUrlParts['host'],
```
Comment (mridang) [inline app/code/community/Nosto/Tagging/Helper/Url.php]: You're missing the port.

File: app/code/community/Nosto/Tagging/Helper/Url.php [hunk 5]
```diff
@@ -260,4 +260,83 @@ public function getFrontPageUrlForStore(Mage_Core_Model_Store $store)
...
+                if (
+                    !empty($oauthPathParts[$index])
+                    && $basePathPart === $oauthPathParts[$index]) {
+                    unset($oauthPathParts[$index]);
+                }
+            }
+            $newPathParts = array_merge($basePathParts, $oauthPathParts);
+            $newUrlParts = array(
+                'scheme' => $oauthUrlParts['scheme'],
+                'host' => $oauthUrlParts['host'],
```
Comment (mridang) [inline app/code/community/Nosto/Tagging/Helper/Url.php]: You're missing the port.

Comment (mridang) [inline app/code/community/Nosto/Tagging/Helper/Url.php]: Here's a reference: https://gist.github.com/amnuts/7598576

File: app/code/community/Nosto/Tagging/Helper/Url.php [hunk 6]
```diff
@@ -250,14 +244,52 @@ public function removeQueryParamFromUrl($url, $param)
...
      * @return string
      */
-    public function getFrontPageUrlForStore(Mage_Core_Model_Store $store)
+    public function getOauthRedirectUrl(Mage_Core_Model_Store $store)
     {
+        $url = Mage::getUrl(
+            'nosto/oauth',
+            array(
+                '_store' => $store->getId(),
+                '_store_to_url' => true,
```
Comment (mridang) [inline app/code/community/Nosto/Tagging/Helper/Url.php]: Move to constants

File: app/code/community/Nosto/Tagging/Helper/Url.php [hunk 7]
```diff
@@ -250,14 +244,52 @@ public function removeQueryParamFromUrl($url, $param)
...
+                '_type' => Mage_Core_Model_Store::URL_TYPE_LINK,
```
Comment (mridang) [inline app/code/community/Nosto/Tagging/Helper/Url.php]: Explain why we don't want to use the `nosid`

File: app/code/community/Nosto/Tagging/Model/Observer.php [hunk 8]
```diff
@@ -153,18 +156,20 @@ public function sendProductDelete(Varien_Event_Observer $observer)
...
                 $model->setProductId($product->getId());
-
                 try {
                     $service = new NostoOperationProduct($account);
                     $service->addProduct($model);
                     $service->delete();
                 } catch (NostoException $e) {
                     Mage::log("\n" . $e, Zend_Log::ERR, 'nostotagging.log');
                 }
+                $emulation->startEnvironmentEmulation($env);
```
Comment (mridang) [inline app/code/community/Nosto/Tagging/Model/Observer.php]: Shouldn't this be `stopEmulation`?

Comment (mridang) [inline app/code/community/Nosto/Tagging/Model/Observer.php]: This could be moved to `finally` block

File: app/code/community/Nosto/Tagging/Block/Adminhtml/Iframe.php [hunk 9]
```diff
@@ -80,11 +80,16 @@ public function getIframeUrl()
...
+        /* @var Mage_Core_Model_App_Emulation $emulation */
+        $emulation = Mage::getSingleton('core/app_emulation');
+        $env = $emulation->startEnvironmentEmulation($store->getId());
         /** @var Nosto_Tagging_Helper_Account $helper */
         $helper = Mage::helper('nosto_tagging/account');
         $account = $helper->find($store);
-        return $this->_iframeUrl = $helper
-            ->getIframeUrl($store, $account, $params);
+        $this->_iframeUrl = $helper->getIframeUrl($store, $account, $params);
+        $emulation->stopEnvironmentEmulation($env);
```
Comment (mridang) [inline app/code/community/Nosto/Tagging/Block/Adminhtml/Iframe.php]: I would wrap this in a `try` and `finally` to be sure that the context is always cleared.

File: app/code/community/Nosto/Tagging/Model/Observer.php (hunk 8 above)
Comment (hannunosto) [inline app/code/community/Nosto/Tagging/Model/Observer.php]: `finally` keyword is only available in php > 5.5. and we'd like to keep the support for PHP 5.4. similar to Magento.

File: app/code/community/Nosto/Tagging/Block/Adminhtml/Iframe.php (hunk 9 above)
Comment (mridang) [inline app/code/community/Nosto/Tagging/Block/Adminhtml/Iframe.php]: Okay, we can't do this due to the 5.4 compat.
