### PR TITLE
Check nosto dependencies before running

### LINKED ISSUE #297: Check that Nosto's PHP SDK is loaded in bootstrap
Check PHP SDK is loaded before building use agent (https://github.com/Nosto/nosto-magento/blob/develop/app/code/community/Nosto/Tagging/bootstrap.php#L30). If PHP SDK is not loaded throw an exception that tells to run composer install & update lib

### PR DESCRIPTION
**Pull request by chenliangde**
Closes #297

### CODE REVIEW

File: app/code/community/Nosto/Tagging/controllers/Adminhtml/NostoController.php [hunk 1]
```diff
@@ -81,6 +81,17 @@ public function redirectProxyAction()
      */
     public function indexAction()
     {
+        if (!class_exists ( 'Nosto_Nosto' , true)) {
```
Comment (mridang) [inline app/code/community/Nosto/Tagging/controllers/Adminhtml/NostoController.php]: No spaces before and after the brackets.

File: app/code/community/Nosto/Tagging/controllers/Adminhtml/NostoController.php [hunk 2]
```diff
@@ -81,6 +81,17 @@ public function redirectProxyAction()
...
+            Mage::getSingleton('core/session')->addError(
```
Comment (mridang) [inline app/code/community/Nosto/Tagging/controllers/Adminhtml/NostoController.php]: I think you should localise this. `_('something')`

File: app/code/community/Nosto/Tagging/Helper/Module.php [hunk 3]
```diff
@@ -49,6 +49,20 @@ class Nosto_Tagging_Helper_Module extends Mage_Core_Helper_Abstract
...
+     *
+     * @param null $moduleName
+     * @return bool
+     */
+    public function isModuleEnabled($moduleName = null)
+    {
+        if (!class_exists ( 'Nosto_Nosto' , true)) {
+            return false;
+        }
+        return parent::isModuleEnabled($moduleName);
```
Comment (mridang) [inline app/code/community/Nosto/Tagging/Helper/Module.php]: Newline before.

File: app/code/community/Nosto/Tagging/Helper/Module.php [hunk 4]
```diff
@@ -49,6 +49,20 @@ class Nosto_Tagging_Helper_Module extends Mage_Core_Helper_Abstract
...
 
     /**
+     * check if the nosto module is enable. And if the dependencies for nosto are missing, return false as well
+     *
+     * @param null $moduleName
+     * @return bool
+     */
+    public function isModuleEnabled($moduleName = null)
+    {
+        if (!class_exists ( 'Nosto_Nosto' , true)) {
```
Comment (mridang) [inline app/code/community/Nosto/Tagging/Helper/Module.php]: Spacing.

File: app/code/community/Nosto/Tagging/Block/Cart.php [hunk 5]
```diff
@@ -45,7 +45,7 @@ protected function _toHtml()
     {
         /** @var Nosto_Tagging_Helper_Account $helper */
         $helper = Mage::helper('nosto_tagging/account');
-        if (!Mage::helper('nosto_tagging')->isModuleEnabled() || !$helper->existsAndIsConnected()) {
+        if (!Mage::helper('nosto_tagging/module')->isModuleEnabled() || !$helper->existsAndIsConnected()) {
```
Comment (mridang) [inline app/code/community/Nosto/Tagging/Block/Cart.php]: Move to new line.
