### PR TITLE
Fix saving simple product that has parent in a website without permission for the current user

### LINKED ISSUE #444: Nosto is loading all the parent products when we save one of the child ones, causing a permissions issue
**Information:**

- Magento Enterprise Edition 1.14.3.9
- Magento with multiple websites and store views
- Admin users in a Role with restricted access to some web sites
- Nosto module v3.7.4

When we save a simple product child of some configurables, Nosto is loading all the parent configurable products (event catalog_product_save_commit_after). If the current admin user have restricted access to specific web sites and one of this configurable products exist only in one of the restricted website, Magento throws the error "Not enough permissions to view this item." fired by the Enterprise_AdminGws core module.

Possible related commit: https://github.com/Nosto/nosto-magento/commit/b3bab031ae301ddd2e86b0ba8b50541547a9434c

**Exception log**
> 2018-10-25T10:42:38+01:00 ERR (3): 
exception 'Enterprise_AdminGws_Controller_Exception' with message 'Not enough permissions to view this item.' in /app/Mage.php:580
Stack trace:
#0 /app/code/core/Enterprise/AdminGws/Model/Models.php(1200): Mage::exception('Enterprise_Admi...', 'Not enough perm...')
#1 /app/code/core/Enterprise/AdminGws/Model/Models.php(240): Enterprise_AdminGws_Model_Models->_throwLoad()
#2 /app/code/core/Enterprise/AdminGws/Model/Observer.php(580): Enterprise_AdminGws_Model_Models->catalogProductLoadAfter(Object(Mage_Catalog_Model_Product))
#3 /app/code/core/Enterprise/AdminGws/Model/Observer.php(382): Enterprise_AdminGws_Model_Observer->_invokeCallback('catalogProductL...', 'enterprise_admi...', Object(Mage_Catalog_Model_Product))
#4 /app/code/core/Mage/Core/Model/App.php(1358): Enterprise_AdminGws_Model_Observer->validateModelLoadAfter(Object(Varien_Event_Observer))
#5 /app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Enterprise_AdminGws_Model_Observer), 'validateModelLo...', Object(Varien_Event_Observer))
#6 /app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('model_load_afte...', Array)
#7 /app/code/core/Mage/Core/Model/Abstract.php(266): Mage::dispatchEvent('model_load_afte...', Array)
#8 /app/code/core/Mage/Catalog/Model/Product.php(596): Mage_Core_Model_Abstract->_afterLoad()
#9 /app/code/core/Mage/Core/Model/Abstract.php(226): Mage_Catalog_Model_Product->_afterLoad()
#10 /app/code/community/Nosto/Tagging/Util/Product.php(90): Mage_Core_Model_Abstract->load('10503')
#11 /app/code/community/Nosto/Tagging/Model/Service/Product.php(76): Nosto_Tagging_Util_Product::toParentProducts(Object(Mage_Catalog_Model_Product))
#12 /app/code/community/Nosto/Tagging/Model/Service/Product.php(162): Nosto_Tagging_Model_Service_Product->update(Array)
#13 /app/code/community/Nosto/Tagging/Model/Observer/Product.php(67): Nosto_Tagging_Model_Service_Product->updateProduct(Object(Mage_Catalog_Model_Product))
#14 /app/code/core/Mage/Core/Model/App.php(1358): Nosto_Tagging_Model_Observer_Product->sendProductUpdate(Object(Varien_Event_Observer))
#15 /app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Nosto_Tagging_Model_Observer_Product), 'sendProductUpda...', Object(Varien_Event_Observer))
#16 /app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('catalog_product...', Array)

KR.

### PR DESCRIPTION
**Pull request by supercid**
Catch exception thrown by Magento enterprise when user has no access to parent product that’s in a different website.
Closes #444

### CODE REVIEW

File: app/code/community/Nosto/Tagging/Util/Product.php [hunk 1]
```diff
@@ -75,8 +75,13 @@ public static function toParentProducts(Mage_Catalog_Model_Product $product)
             $parentIds = $model->getParentIdsByChild($product->getId());
             if (!empty($parentIds)) {
                 foreach ($parentIds as $productId) {
-                    $configurable = Mage::getModel('catalog/product')->load($productId);
-                    $parents[] = $configurable;
+                    try {
+                        $configurable = Mage::getModel('catalog/product')->load($productId);
+                        $parents[] = $configurable;
+                    } catch (\Exception $e) {
+                        Nosto_Tagging_Helper_Log::exception($e);
```
Comment (hannunosto) [inline app/code/community/Nosto/Tagging/Util/Product.php]: Add check here which kind of exception was thrown. We only want log the exception if it's something else than `Enterprise_AdminGws_Controller_Exception`

File: app/code/community/Nosto/Tagging/Util/Product.php [hunk 2]
```diff
@@ -75,8 +75,13 @@ public static function toParentProducts(Mage_Catalog_Model_Product $product)
...
+                        continue;
```
Comment (hannunosto) [inline app/code/community/Nosto/Tagging/Util/Product.php]: I think this is redundant as there's no further logic in the loop
