### PR TITLE
hotfix 3.5.5

### LINKED ISSUE #376: Bundle product list price is tagged incorrectly
Bundle product list price is tagged incorrectly. If the option is optional, than is should not be included to the min price. But if all the options are optional, the cheapest option should be take for the price.

### PR DESCRIPTION
**Pull request by chenliangde**
Closes #376

### CODE REVIEW

File: app/code/community/Nosto/Tagging/Helper/Price.php [hunk 1]
```diff
@@ -224,10 +224,16 @@ public function getBundleProductPrices(
             false,
             Mage::helper('catalog/product')->getSkipSaleableCheck()
         );
+        $sumPrice = 0;
         $sumListPrice = 0;
+        $allOptional = true;
         /** @var Mage_Bundle_Model_Option $option */
         foreach ($options as $option) {
             $selections  = $option->getSelections();
```
Comment (supercid) [inline app/code/community/Nosto/Tagging/Helper/Price.php]: You could move this line to be below the if condition, so if it's not required, will jump out of the loop without the attribution

File: app/code/community/Nosto/Tagging/Helper/Price.php [hunk 2]
```diff
@@ -244,6 +250,47 @@ public function getBundleProductPrices(
             }
 
             $sumListPrice += $simpleProductListPrice;
+            $sumPrice += $minSimpleProductPricePrice;
+        }
+
+        //None of them are required, take the cheapest item
+        if ($allOptional) {
```
Comment (supercid) [inline app/code/community/Nosto/Tagging/Helper/Price.php]: Maybe you can avoid looping twice moving these block to the upper foreach loops and using if conditions to filter them and return the cheapest

Comment (chenliangde) [reply app/code/community/Nosto/Tagging/Helper/Price.php]: It will make the loop too complicated ( I couldn't do line 234 with that way). If none of them are mandatory, the first loop doesn't do anything.

File: app/code/community/Nosto/Tagging/Helper/Price.php (hunk 1 above)
Comment (chenliangde) [reply app/code/community/Nosto/Tagging/Helper/Price.php]: Fixed, thanks
